name: Build and Deploy Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Replace with the version you need

      - name: Install dependencies
        run: npm install

      - name: Checkout
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git checkout -b gh-pages

      - name: Pull existing dist branch
        run: git pull origin gh-pages


      - name: Build
        run: npm run build

      - name: Copy dist folder to dist branch
        env:
            GITHUB_TOKEN: ${{ secrets.DIST_TOKENN }}
        run: |
            git add dist -f
            git commit -m 'update dist subtree'
            git push origin gh-pages
